angular.module('BuscaProdutoApp', [])
  .controller('BuscaProdutoController', function($scope) {
    $scope.produtos = [{ codigo: '137263', caption: 'Espelho de bolso duplo', captionSemAcentos: 'Espelho de bolso duplo', dimensions: '(7 x 6,5 x 0,8 cm)' },
{ codigo: '137350A', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '137350B', caption: 'Chaveiro de metal (retangular)', captionSemAcentos: 'Chaveiro de metal (retangular)', dimensions: '(8 x 3 cm)' },
{ codigo: '137350K', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '137350L', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '137350M', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '( cm)' },
{ codigo: '137350P', caption: 'Chaveiro de metal (coração)', captionSemAcentos: 'Chaveiro de metal (coracao)', dimensions: '(8 x 3 cm)' },
{ codigo: '137350R', caption: 'Chaveiro de metal (redondo)', captionSemAcentos: 'Chaveiro de metal (redondo)', dimensions: '(8 x 3 cm)' },
{ codigo: '137535', caption: 'Espelho de bolso', captionSemAcentos: 'Espelho de bolso', dimensions: '(7,5 x 6,5 x 0,5 cm)' },
{ codigo: '138319P', caption: 'Kit pincéis c/ 7 pçs', captionSemAcentos: 'Kit pinceis c/ 7 pcs', dimensions: '(18 x 8 cm)' },
{ codigo: '138319T', caption: 'Kit pincéis c/ 7 pçs', captionSemAcentos: 'Kit pinceis c/ 7 pcs', dimensions: '(18 x 8 cm)' },
{ codigo: '138499A', caption: 'Bloco p/ anotação (azul)', captionSemAcentos: 'Bloco p/ anotacao (azul)', dimensions: '(10 x 10 x 2,7 cm)' },
{ codigo: '138499P', caption: 'Bloco p/ anotação (preto)', captionSemAcentos: 'Bloco p/ anotacao (preto)', dimensions: '(10 x 10 x 2,7 cm)' },
{ codigo: '138801', caption: 'Leque cristal c/ imagem', captionSemAcentos: 'Leque cristal c/ imagem', dimensions: '( cm)' },
{ codigo: '138802', caption: 'Adorno de cristal liso', captionSemAcentos: 'Adorno de cristal liso', dimensions: '( cm)' },
{ codigo: '138804', caption: 'Cachos de uva de cristal', captionSemAcentos: 'Cachos de uva de cristal', dimensions: '( cm)' },
{ codigo: '139385P', caption: 'Jogo de pincéis c/ 5 pçs', captionSemAcentos: 'Jogo de pinceis c/ 5 pcs', dimensions: '(8 x 5,5 x 1,5 cm)' },
{ codigo: '139385T', caption: 'Jogo de pincéis c/ 5 pçs', captionSemAcentos: 'Jogo de pinceis c/ 5 pcs', dimensions: '(8 x 5,5 x 1,5 cm)' },
{ codigo: '139388', caption: 'Kit manicure c/ 6 pçs', captionSemAcentos: 'Kit manicure c/ 6 pcs', dimensions: '(12 x 4,5 cm)' },
{ codigo: '139454', caption: 'Canivete c/ 11 funções', captionSemAcentos: 'Canivete c/ 11 funcoes', dimensions: '(9 x 2,5 x 2,5 cm)' },
{ codigo: '139454A', caption: 'Canivete c/ 11 funções', captionSemAcentos: 'Canivete c/ 11 funcoes', dimensions: '(9 x 2,5 x 2,5 cm)' },
{ codigo: '139482H', caption: 'Chaveiro de metal (retangular)', captionSemAcentos: 'Chaveiro de metal (retangular)', dimensions: '(8 x 3 cm)' },
{ codigo: '139482L', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8,5 x 3 cm)' },
{ codigo: '139482M', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8,5 x 3 cm)' },
{ codigo: '139482R', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '139547A', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(7,5 x 3 cm)' },
{ codigo: '139735', caption: 'Porta foto c/ relógio multifunção', captionSemAcentos: 'Porta foto c/ relogio multifuncao', dimensions: '(18 x 18 x 1,5 cm)' },
{ codigo: '140045', caption: 'Espelho de bolso duplo', captionSemAcentos: 'Espelho de bolso duplo', dimensions: '(7,5 x 6,5 cm)' },
{ codigo: '140047', caption: 'Espelho de bolso duplo', captionSemAcentos: 'Espelho de bolso duplo', dimensions: '(6 x 6 cm)' },
{ codigo: '140068', caption: 'Chaveiro c/ canivete c/ 3 funções', captionSemAcentos: 'Chaveiro c/ canivete c/ 3 funcoes', dimensions: '(6 x 2 x 1,2 cm)' },
{ codigo: '140070', caption: 'Chaveiro c/ canivete c/ 4 funções', captionSemAcentos: 'Chaveiro c/ canivete c/ 4 funcoes', dimensions: '(4,5 x 2,7 x 0,5 cm)' },
{ codigo: '140078', caption: 'Canivete c/ 7 funções', captionSemAcentos: 'Canivete c/ 7 funcoes', dimensions: '(7,5 x 2 x 1,2 cm)' },
{ codigo: '140086', caption: 'Espelho c/ base (redondo)', captionSemAcentos: 'Espelho c/ base (redondo)', dimensions: '(6 cm)' },
{ codigo: '140087', caption: 'Espelho c/ base (quadrado)', captionSemAcentos: 'Espelho c/ base (quadrado)', dimensions: '(8 x 6 cm)' },
{ codigo: '140088', caption: 'Espelho c/ base (oval)', captionSemAcentos: 'Espelho c/ base (oval)', dimensions: '(8 x 6 cm)' },
{ codigo: '140117', caption: 'Kit manicure c/ 6 pçs', captionSemAcentos: 'Kit manicure c/ 6 pcs', dimensions: '(11 x 6 x 1,5 cm)' },
{ codigo: '140117R', caption: 'Kit manicure c/ 6 pçs', captionSemAcentos: 'Kit manicure c/ 6 pcs', dimensions: '(11 x 6 x 1,5 cm)' },
{ codigo: '140117S', caption: 'Kit manicure c/ 6 pçs', captionSemAcentos: 'Kit manicure c/ 6 pcs', dimensions: '(11 x 6 x 1,5 cm)' },
{ codigo: '140117V', caption: 'Kit manicure c/ 6 pçs', captionSemAcentos: 'Kit manicure c/ 6 pcs', dimensions: '(11 x 6 x 1,5 cm)' },
{ codigo: '140121', caption: 'Kit manicure c/ 6 pçs', captionSemAcentos: 'Kit manicure c/ 6 pcs', dimensions: '(12 x 7 cm)' },
{ codigo: '140125A', caption: 'Kit manicure c/ 5 pçs', captionSemAcentos: 'Kit manicure c/ 5 pcs', dimensions: '(9,5 x 6,5 x 2 cm)' },
{ codigo: '140125R', caption: 'Kit manicure c/ 5 pçs', captionSemAcentos: 'Kit manicure c/ 5 pcs', dimensions: '(9,5 x 6,5 x 2 cm)' },
{ codigo: '140125V', caption: 'Kit manicure c/ 5 pçs', captionSemAcentos: 'Kit manicure c/ 5 pcs', dimensions: '(9,5 x 6,5 x 2 cm)' },
{ codigo: '140135', caption: 'Saca rolhas de metal', captionSemAcentos: 'Saca rolhas de metal', dimensions: '(19 x 7 x 1,6 cm)' },
{ codigo: '140153B', caption: 'Porta cartão de metal', captionSemAcentos: 'Porta cartao de metal', dimensions: '(10 x 6 x 0,5 cm)' },
{ codigo: '140231', caption: 'Porta caneta c/ relógio de metal', captionSemAcentos: 'Porta caneta c/ relogio de metal', dimensions: '(12 x 6 x 6,5 cm)' },
{ codigo: '140232', caption: 'Porta caneta c/ relógio de metal', captionSemAcentos: 'Porta caneta c/ relogio de metal', dimensions: '(8,5 x 5 x 9 cm)' },
{ codigo: '140241', caption: 'Espelho c/ aumento e base de alumínio', captionSemAcentos: 'Espelho c/ aumento e base de aluminio', dimensions: '(12,5 x 9,5 cm)' },
{ codigo: '140274', caption: 'Espelho c/ aumento e base (pequeno)', captionSemAcentos: 'Espelho c/ aumento e base (pequeno)', dimensions: '(15 cm)' },
{ codigo: '140275', caption: 'Espelho c/ aumento e base (grande)', captionSemAcentos: 'Espelho c/ aumento e base (grande)', dimensions: '(20 cm)' },
{ codigo: '140276', caption: 'Espelho c/ aumento e base (médio)', captionSemAcentos: 'Espelho c/ aumento e base (medio)', dimensions: '(17,5 cm)' },
{ codigo: '140288', caption: 'Canivete c/ 8 funções e alicate', captionSemAcentos: 'Canivete c/ 8 funcoes e alicate', dimensions: '(18 x 6 x 2,3 cm)' },
{ codigo: '140303', caption: 'Chaveiro de metal bola de futebol', captionSemAcentos: 'Chaveiro de metal bola de futebol', dimensions: '(8,5 x 3,5 cm)' },
{ codigo: '140304', caption: 'Chaveiro de metal jogador', captionSemAcentos: 'Chaveiro de metal jogador', dimensions: '(8 x 3,5 cm)' },
{ codigo: '140304A', caption: 'Chaveiro de metal jogador', captionSemAcentos: 'Chaveiro de metal jogador', dimensions: '(7 x 3 cm)' },
{ codigo: '140304B', caption: 'Chaveiro de metal jogador', captionSemAcentos: 'Chaveiro de metal jogador', dimensions: '(7 x 3 cm)' },
{ codigo: '140310', caption: 'Kit ferramentas c/ 25 pçs e estojo', captionSemAcentos: 'Kit ferramentas c/ 25 pcs e estojo', dimensions: '(30 x 15,5 cm)' },
{ codigo: '140313', caption: 'Coqueteleira de inox 750 ml', captionSemAcentos: 'Coqueteleira de inox 750 ml', dimensions: '(21 x 8,5 cm)' },
{ codigo: '140314', caption: 'Coqueteleira de inox 550 ml', captionSemAcentos: 'Coqueteleira de inox 550 ml', dimensions: '(18 x 8,5 cm)' },
{ codigo: '140395', caption: 'Cantil de inox 750 ml c/ estojo', captionSemAcentos: 'Cantil de inox 750 ml c/ estojo', dimensions: '(29 x 7,5 cm)' },
{ codigo: '140396', caption: 'Chaveiro de metal (santos)', captionSemAcentos: 'Chaveiro de metal (santos)', dimensions: '(7 x 3 cm)' },
{ codigo: '140399', caption: 'Necessaire c/ 5 pçs', captionSemAcentos: 'Necessaire c/ 5 pcs', dimensions: '(21 x 13 cm)' },
{ codigo: '140401', caption: 'Mouse pad c/ calculadora', captionSemAcentos: 'Mouse pad c/ calculadora', dimensions: '(29,5 x 20 cm)' },
{ codigo: '140402', caption: 'Mouse pad c/ calculadora', captionSemAcentos: 'Mouse pad c/ calculadora', dimensions: '(27 x 20 cm)' },
{ codigo: '140406', caption: 'Coqueteleira de inox 350 ml', captionSemAcentos: 'Coqueteleira de inox 350 ml', dimensions: '(16,5 x 8 cm)' },
{ codigo: '140873A', caption: 'Chaveiro abridor de garrafa', captionSemAcentos: 'Chaveiro abridor de garrafa', dimensions: '(8 x 1,5 cm)' },
{ codigo: '140873P', caption: 'Chaveiro abridor de garrafa', captionSemAcentos: 'Chaveiro abridor de garrafa', dimensions: '(8 x 1,5 cm)' },
{ codigo: '140873S', caption: 'Chaveiro abridor de garrafa', captionSemAcentos: 'Chaveiro abridor de garrafa', dimensions: '(8 x 1,5 cm)' },
{ codigo: '140873V', caption: 'Chaveiro abridor de garrafa', captionSemAcentos: 'Chaveiro abridor de garrafa', dimensions: '(8 x 1,5 cm)' },
{ codigo: '140879', caption: 'Kit manicure c/ 12 pçs', captionSemAcentos: 'Kit manicure c/ 12 pcs', dimensions: '(18,5 x 14 x 3 cm)' },
{ codigo: '140884', caption: 'Alicate multifunção p/ pescaria', captionSemAcentos: 'Alicate multifuncao p/ pescaria', dimensions: '(22 x 7 x 1,5 cm)' },
{ codigo: '140888', caption: 'Lanterna c/ relógio e bússola', captionSemAcentos: 'Lanterna c/ relogio e bussola', dimensions: '(10 x 3 x 1,5 cm)' },
{ codigo: '140890', caption: 'Rádio c/ relógio digital de plástico', captionSemAcentos: 'Radio c/ relogio digital de plastico', dimensions: '(15,5 x 10 x 2 cm)' },
{ codigo: '140895', caption: 'Relógio digital c/ porta foto', captionSemAcentos: 'Relogio digital c/ porta foto', dimensions: '(8 x 8 x 3 cm)' },
{ codigo: '140897', caption: 'Rádio de plástico', captionSemAcentos: 'Radio de plastico', dimensions: '( cm)' },
{ codigo: '140900', caption: 'Rádio de plástico', captionSemAcentos: 'Radio de plastico', dimensions: '(12 x 10 x 6,5 cm)' },
{ codigo: '140901', caption: 'Moedor de pimenta a pilha', captionSemAcentos: 'Moedor de pimenta a pilha', dimensions: '(23,5 x 5,5 cm)' },
{ codigo: '140902A', caption: 'Caneca plástica 450 ml', captionSemAcentos: 'Caneca plastica 450 ml', dimensions: '(18 x 11,5 x 8 cm)' },
{ codigo: '140902G', caption: 'Caneca plástica 450 ml', captionSemAcentos: 'Caneca plastica 450 ml', dimensions: '(18 x 11,5 x 8 cm)' },
{ codigo: '140902T', caption: 'Caneca plástica 450 ml', captionSemAcentos: 'Caneca plastica 450 ml', dimensions: '(18 x 11,5 x 8 cm)' },
{ codigo: '140902V', caption: 'Caneca plástica 450 ml', captionSemAcentos: 'Caneca plastica 450 ml', dimensions: '(18 x 11,5 x 8 cm)' },
{ codigo: '140918', caption: 'Calculadora de plástico', captionSemAcentos: 'Calculadora de plastico', dimensions: '(9,5 x 7 x 1 cm)' },
{ codigo: '140919', caption: 'Relógio multifunção de plástico', captionSemAcentos: 'Relogio multifuncao de plastico', dimensions: '(9 x 8 x 2,5 cm)' },
{ codigo: '140922', caption: 'Relógio multifunção c/ porta canetas', captionSemAcentos: 'Relogio multifuncao c/ porta canetas', dimensions: '(11,5 x 9,5 x 5 cm)' },
{ codigo: '140923', caption: 'Relógio c/ porta foto e porta canetas', captionSemAcentos: 'Relogio c/ porta foto e porta canetas', dimensions: '(14,5 x 13 x 1,5 cm)' },
{ codigo: '140924', caption: 'Relógio multifunção de plástico', captionSemAcentos: 'Relogio multifuncao de plastico', dimensions: '(9,5 x 8 x 2,5 cm)' },
{ codigo: '140926', caption: 'Lupa 75mm c/ luz', captionSemAcentos: 'Lupa 75mm c/ luz', dimensions: '(17 x 8 x 3 cm)' },
{ codigo: '140927', caption: 'Lupa 90mm c/ luz', captionSemAcentos: 'Lupa 90mm c/ luz', dimensions: '(19 x 9,5 x 3 cm)' },
{ codigo: '140943', caption: 'Espelho de bolso duplo', captionSemAcentos: 'Espelho de bolso duplo', dimensions: '(8,5 x 7 cm)' },
{ codigo: '140944', caption: 'Espelho de bolso duplo', captionSemAcentos: 'Espelho de bolso duplo', dimensions: '(7 x 6 cm)' },
{ codigo: '140963A', caption: 'Kit caneta e lapiseira com chaveiro e canivete', captionSemAcentos: 'Kit caneta e lapiseira com chaveiro e canivete', dimensions: '(17,5 x 14 cm)' },
{ codigo: '140963B', caption: 'Kit caneta e lapiseira com chaveiro e canivete', captionSemAcentos: 'Kit caneta e lapiseira com chaveiro e canivete', dimensions: '(17,5 x 14 cm)' },
{ codigo: '140964', caption: 'Kit caneta e lapiseira com chaveiro', captionSemAcentos: 'Kit caneta e lapiseira com chaveiro', dimensions: '(18 x 11 cm)' },
{ codigo: '140964A', caption: 'Kit caneta e lapiseira com chaveiro', captionSemAcentos: 'Kit caneta e lapiseira com chaveiro', dimensions: '(17,5 x 11 cm)' },
{ codigo: '140964B', caption: 'Kit caneta e lapiseira com chaveiro', captionSemAcentos: 'Kit caneta e lapiseira com chaveiro', dimensions: '(17,5 x 11 cm)' },
{ codigo: '140966', caption: 'Rádio relógio de plástico', captionSemAcentos: 'Radio relogio de plastico', dimensions: '(13 x 8,5 x 8 cm)' },
{ codigo: '140970', caption: 'Porta tempero de plástico c/ 2 pçs', captionSemAcentos: 'Porta tempero de plastico c/ 2 pcs', dimensions: '(10 x 4 cm)' },
{ codigo: '140971', caption: 'Moedor de pimenta plástico', captionSemAcentos: 'Moedor de pimenta plastico', dimensions: '(17 x 6 cm)' },
{ codigo: '140975A', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '140975E', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '140975G', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '140975L', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '140975M', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '140975T', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '140975V', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '140975W', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '141001', caption: 'Mini luminária plástica p/ livro', captionSemAcentos: 'Mini luminaria plastica p/ livro', dimensions: '(5,5 x 5 x 2 cm)' },
{ codigo: '141018', caption: 'Squeeze de inox 400 ml', captionSemAcentos: 'Squeeze de inox 400 ml', dimensions: '(17 x 6,5 cm)' },
{ codigo: '141018A', caption: 'Squeeze de inox 400 ml', captionSemAcentos: 'Squeeze de inox 400 ml', dimensions: '(17 x 6,5 cm)' },
{ codigo: '141018B', caption: 'Squeeze de inox 400 ml', captionSemAcentos: 'Squeeze de inox 400 ml', dimensions: '(17 x 6,5 cm)' },
{ codigo: '141018G', caption: 'Squeeze de inox 400 ml', captionSemAcentos: 'Squeeze de inox 400 ml', dimensions: '(17 x 6,5 cm)' },
{ codigo: '141018V', caption: 'Squeeze de inox 400 ml', captionSemAcentos: 'Squeeze de inox 400 ml', dimensions: '(17 x 6,5 cm)' },
{ codigo: '141019', caption: 'Squeeze de inox 600 ml', captionSemAcentos: 'Squeeze de inox 600 ml', dimensions: '(21 x 7 cm)' },
{ codigo: '141019A', caption: 'Squeeze de inox 600 ml', captionSemAcentos: 'Squeeze de inox 600 ml', dimensions: '(21 x 7 cm)' },
{ codigo: '141019B', caption: 'Squeeze de inox 600 ml', captionSemAcentos: 'Squeeze de inox 600 ml', dimensions: '(21 x 7 cm)' },
{ codigo: '141019G', caption: 'Squeeze de inox 600 ml', captionSemAcentos: 'Squeeze de inox 600 ml', dimensions: '(21 x 7 cm)' },
{ codigo: '141019V', caption: 'Squeeze de inox 600 ml', captionSemAcentos: 'Squeeze de inox 600 ml', dimensions: '(21 x 7 cm)' },
{ codigo: '141025', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '141173', caption: 'Luminária de plástico p/ leitura', captionSemAcentos: 'Luminaria de plastico p/ leitura', dimensions: '(12 x 3,5 x 2 cm)' },
{ codigo: '141175', caption: 'Rádio de plástico', captionSemAcentos: 'Radio de plastico', dimensions: '( cm)' },
{ codigo: '141176', caption: 'Relógio multifunção plástico', captionSemAcentos: 'Relogio multifuncao plastico', dimensions: '(11 x 6 x 3 cm)' },
{ codigo: '141177', caption: 'Rádio relógio multifunção plástico', captionSemAcentos: 'Radio relogio multifuncao plastico', dimensions: '(19,5 x 7 cm)' },
{ codigo: '141193', caption: 'Espelho c/ aumento e base metal', captionSemAcentos: 'Espelho c/ aumento e base metal', dimensions: '(12,5 cm)' },
{ codigo: '141200', caption: 'Kit churrasco c/ 17 pçs', captionSemAcentos: 'Kit churrasco c/ 17 pcs', dimensions: '(47 x 24 x 8 cm)' },
{ codigo: '141222', caption: 'Relógio de plástico c/ porta foto', captionSemAcentos: 'Relogio de plastico c/ porta foto', dimensions: '(9 x 5,5 x 2,5 cm)' },
{ codigo: '141229', caption: 'Canivete c/ 7 funções', captionSemAcentos: 'Canivete c/ 7 funcoes', dimensions: '(9 x 2,5 x 2 cm)' },
{ codigo: '141231', caption: 'Balança p/ cozinha digital', captionSemAcentos: 'Balanca p/ cozinha digital', dimensions: '(19 x 15 x 4 cm)' },
{ codigo: '141232', caption: 'Balança p/ cozinha digital', captionSemAcentos: 'Balanca p/ cozinha digital', dimensions: '(24 x 17 x 4 cm)' },
{ codigo: '141235', caption: 'Jogo de ferramentas c/ 6 pçs', captionSemAcentos: 'Jogo de ferramentas c/ 6 pcs', dimensions: '(13,5 x 9 x 2 cm)' },
{ codigo: '141237', caption: 'Espelho de bolso duplo c/ luz', captionSemAcentos: 'Espelho de bolso duplo c/ luz', dimensions: '(7 x 2 cm)' },
{ codigo: '141244A', caption: 'Bloco p/ anotação (azul)', captionSemAcentos: 'Bloco p/ anotacao (azul)', dimensions: '(10 x 7 x 3 cm)' },
{ codigo: '141244P', caption: 'Bloco p/ anotação (preto)', captionSemAcentos: 'Bloco p/ anotacao (preto)', dimensions: '(10 x 7 x 3 cm)' },
{ codigo: '141248', caption: 'Jogo de xadrez de plástico', captionSemAcentos: 'Jogo de xadrez de plastico', dimensions: '(16 x 8 x 2,5 cm)' },
{ codigo: '141253', caption: 'Régua plástica c/ calculadora', captionSemAcentos: 'Regua plastica c/ calculadora', dimensions: '(20 x 5 cm)' },
{ codigo: '141256', caption: 'Mini rádio FM auto procura', captionSemAcentos: 'Mini radio FM auto procura', dimensions: '( cm)' },
{ codigo: '141263', caption: 'Espelho de bolso duplo c/ aumento', captionSemAcentos: 'Espelho de bolso duplo c/ aumento', dimensions: '(8 x 6,5 cm)' },
{ codigo: '141264', caption: 'Espelho de bolso duplo c/ luz', captionSemAcentos: 'Espelho de bolso duplo c/ luz', dimensions: '(7 x 7 x 2 cm)' },
{ codigo: '141266', caption: 'Cantil de inox 1 litro c/ estojo', captionSemAcentos: 'Cantil de inox 1 litro c/ estojo', dimensions: '(32,5 x 8 cm)' },
{ codigo: '141267', caption: 'Moedor de pimenta de metal', captionSemAcentos: 'Moedor de pimenta de metal', dimensions: '(15 x 3 cm)' },
{ codigo: '141268', caption: 'Kit ferramentas c/ 8 pçs', captionSemAcentos: 'Kit ferramentas c/ 8 pcs', dimensions: '(9 x 9 x 3 cm)' },
{ codigo: '141275M', caption: 'Kit queijo c/ 6 pçs (ímã)', captionSemAcentos: 'Kit queijo c/ 6 pcs (ima)', dimensions: '(20 x 20 x 8 cm)' },
{ codigo: '141276A', caption: 'Kit queijo c/ 5 pçs', captionSemAcentos: 'Kit queijo c/ 5 pcs', dimensions: '(17 x 17 x 5,5 cm)' },
{ codigo: '141283', caption: 'Lanterna c/ kit ferramentas', captionSemAcentos: 'Lanterna c/ kit ferramentas', dimensions: '(19 x 12 x 8 cm)' },
{ codigo: '141284', caption: 'Lanterna c/ kit ferramentas', captionSemAcentos: 'Lanterna c/ kit ferramentas', dimensions: '(19 x 12 x 8 cm)' },
{ codigo: '141295', caption: 'Caneca de inox e plástico 400 ml', captionSemAcentos: 'Caneca de inox e plastico 400 ml', dimensions: '(16,5 x 11,5 x 8 cm)' },
{ codigo: '141303', caption: 'Relógio multifunção de plástico', captionSemAcentos: 'Relogio multifuncao de plastico', dimensions: '(9 x 9 x 3,5 cm)' },
{ codigo: '141306', caption: 'Cantil de inox 235 ml', captionSemAcentos: 'Cantil de inox 235 ml', dimensions: '(13,5 x 9 x 2,5 cm)' },
{ codigo: '141307', caption: 'Cantil de inox 200 ml', captionSemAcentos: 'Cantil de inox 200 ml', dimensions: '(12 x 9 x 2,5 cm)' },
{ codigo: '141309P', caption: 'Kit pincéis c/ 5 pçs', captionSemAcentos: 'Kit pinceis c/ 5 pcs', dimensions: '(14,5 x 8 cm)' },
{ codigo: '141309T', caption: 'Kit pincéis c/ 5 pçs', captionSemAcentos: 'Kit pinceis c/ 5 pcs', dimensions: '(14,5 x 8 cm)' },
{ codigo: '141312', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(6 x 3 cm)' },
{ codigo: '141316', caption: 'Relógio multifunção com porta foto', captionSemAcentos: 'Relogio multifuncao com porta foto', dimensions: '(15,5 x 11 x 1,5 cm)' },
{ codigo: '141705', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8,5 x 3 cm)' },
{ codigo: '141706', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8,5 x 2,7 cm)' },
{ codigo: '141708B', caption: 'Espelho e escova de bolso', captionSemAcentos: 'Espelho e escova de bolso', dimensions: '(14 x 6,8 cm)' },
{ codigo: '141709', caption: 'Mosquetão c/ bússola', captionSemAcentos: 'Mosquetao c/ bussola', dimensions: '(7 x 3 cm)' },
{ codigo: '141713', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(8,5 x 3 cm)' },
{ codigo: '141716', caption: 'Cantil de inox 265 ml', captionSemAcentos: 'Cantil de inox 265 ml', dimensions: '(15 x 9,5 x 2,5 cm)' },
{ codigo: '141719', caption: 'Cantil de inox 500 ml c/ estojo', captionSemAcentos: 'Cantil de inox 500 ml c/ estojo', dimensions: '(24,5 x 7 cm)' },
{ codigo: '141730', caption: 'Saca rolhas de metal', captionSemAcentos: 'Saca rolhas de metal', dimensions: '(20,5 x 10 cm)' },
{ codigo: '141733A', caption: 'Kit queijo c/ 5 pçs', captionSemAcentos: 'Kit queijo c/ 5 pcs', dimensions: '(26 x 3 cm)' },
{ codigo: '141734', caption: 'Kit churrasco c/ avental', captionSemAcentos: 'Kit churrasco c/ avental', dimensions: '(60 x 42 cm)' },
{ codigo: '141739', caption: 'Saca rolhas de metal c/ base', captionSemAcentos: 'Saca rolhas de metal c/ base', dimensions: '(8,5 x 15 x 7,5 cm)' },
{ codigo: '141742', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(19,5 x 6,5 cm)' },
{ codigo: '141742A', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(19,5 x 6,5 cm)' },
{ codigo: '141742B', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(19,5 x 6,5 cm)' },
{ codigo: '141742G', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(19,5 x 6,5 cm)' },
{ codigo: '141742L', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(19,5 x 6,5 cm)' },
{ codigo: '141742V', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(19,5 x 6,5 cm)' },
{ codigo: '141742W', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(19,5 x 6,5 cm)' },
{ codigo: '141742Y', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(19,5 x 6,5 cm)' },
{ codigo: '141764', caption: 'Conjunto mini ferramentas de precisão', captionSemAcentos: 'Conjunto mini ferramentas de precisao', dimensions: '(10,5 x 4 x 3,5 cm)' },
{ codigo: '141765', caption: 'Jogo de ferramentas c/ 6 pçs e estojo', captionSemAcentos: 'Jogo de ferramentas c/ 6 pcs e estojo', dimensions: '(15 x 10,5 cm)' },
{ codigo: '141767C', caption: 'Kit costura com estojo', captionSemAcentos: 'Kit costura com estojo', dimensions: '(6,5 x 6,5 x 1,5 cm)' },
{ codigo: '141767P', caption: 'Kit costura com estojo', captionSemAcentos: 'Kit costura com estojo', dimensions: '(6,5 x 6,5 x 1,5 cm)' },
{ codigo: '141771', caption: 'Alicate com canivete e prendedor', captionSemAcentos: 'Alicate com canivete e prendedor', dimensions: '(11,5 x 3,5 x 1,5 cm)' },
{ codigo: '141772', caption: 'Kit manicure c/ 8 pçs e estojo', captionSemAcentos: 'Kit manicure c/ 8 pcs e estojo', dimensions: '(14 x 8,5 x 2,8 cm)' },
{ codigo: '141773B', caption: 'Kit manicure c/ 7 pçs', captionSemAcentos: 'Kit manicure c/ 7 pcs', dimensions: '(11 x 7 x 2,3 cm)' },
{ codigo: '141773C', caption: 'Kit manicure c/ 7 pçs', captionSemAcentos: 'Kit manicure c/ 7 pcs', dimensions: '(11 x 7 x 2,3 cm)' },
{ codigo: '141773P', caption: 'Kit manicure c/ 7 pçs', captionSemAcentos: 'Kit manicure c/ 7 pcs', dimensions: '(11 x 7 x 2,3 cm)' },
{ codigo: '141773R', caption: 'Kit manicure c/ 7 pçs', captionSemAcentos: 'Kit manicure c/ 7 pcs', dimensions: '(11 x 7 x 2,3 cm)' },
{ codigo: '141773V', caption: 'Kit manicure c/ 7 pçs', captionSemAcentos: 'Kit manicure c/ 7 pcs', dimensions: '(11 x 7 x 2,3 cm)' },
{ codigo: '141774', caption: 'Alicate multifunção', captionSemAcentos: 'Alicate multifuncao', dimensions: '(10,5 x 6 x 1,5 cm)' },
{ codigo: '141776', caption: 'Kit manicure c/ 9 pçs e estojo', captionSemAcentos: 'Kit manicure c/ 9 pcs e estojo', dimensions: '(14,5 x 7,5 x 2,5 cm)' },
{ codigo: '141778', caption: 'Lanterna de plástico manual', captionSemAcentos: 'Lanterna de plastico manual', dimensions: '(12 x 3,5 x 6,5 cm)' },
{ codigo: '141780', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(7 x 3 cm)' },
{ codigo: '141780B', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(7,5 x 3 cm)' },
{ codigo: '141780C', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(6,5 x 3 cm)' },
{ codigo: '141780D', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(7,5 x 3 cm)' },
{ codigo: '141780R', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(6,5 x 3 cm)' },
{ codigo: '141796P', caption: 'Mouse pad', captionSemAcentos: 'Mouse pad', dimensions: '(24,5 x 21 cm)' },
{ codigo: '141797', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(8,5 x 3 cm)' },
{ codigo: '141808', caption: 'Vaporizador de perfume 5 ml', captionSemAcentos: 'Vaporizador de perfume 5 ml', dimensions: '(8,3 x 1,8 cm)' },
{ codigo: '141809', caption: 'Vaporizador de perfume 8 ml', captionSemAcentos: 'Vaporizador de perfume 8 ml', dimensions: '(9 x 2,3 cm)' },
{ codigo: '141810', caption: 'Kit caneta e lapiseira com chaveiro e canivete', captionSemAcentos: 'Kit caneta e lapiseira com chaveiro e canivete', dimensions: '(18,5 x 15,5 cm)' },
{ codigo: '141810A', caption: 'Kit caneta e lapiseira com chaveiro e canivete', captionSemAcentos: 'Kit caneta e lapiseira com chaveiro e canivete', dimensions: '(18,5 x 15,5 cm)' },
{ codigo: '141810B', caption: 'Kit caneta e lapiseira com chaveiro e canivete', captionSemAcentos: 'Kit caneta e lapiseira com chaveiro e canivete', dimensions: '(18,5 x 15,5 cm)' },
{ codigo: '141813', caption: 'Caneca de inox 450 ml', captionSemAcentos: 'Caneca de inox 450 ml', dimensions: '(18 x 12 x 8 cm)' },
{ codigo: '141816', caption: 'Saca rolhas de metal', captionSemAcentos: 'Saca rolhas de metal', dimensions: '(13 x 4 x 0,6 cm)' },
{ codigo: '141821A', caption: 'Caneca portátil plástica', captionSemAcentos: 'Caneca portatil plastica', dimensions: '(14 x 14 x 10,5 cm)' },
{ codigo: '141821T', caption: 'Caneca portátil plástica', captionSemAcentos: 'Caneca portatil plastica', dimensions: '(14 x 14 x 10,5 cm)' },
{ codigo: '141821V', caption: 'Caneca portátil plástica', captionSemAcentos: 'Caneca portatil plastica', dimensions: '(14 x 14 x 10,5 cm)' },
{ codigo: '141823', caption: 'Porta caneta com relógio digital', captionSemAcentos: 'Porta caneta com relogio digital', dimensions: '(11 x 8,5 cm)' },
{ codigo: '141824', caption: 'Moedor de pimenta a pilha', captionSemAcentos: 'Moedor de pimenta a pilha', dimensions: '(22,5 x 5,2 cm)' },
{ codigo: '141825P', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(25 x 7,5 cm)' },
{ codigo: '141830', caption: 'Pincel p/ cosméticos', captionSemAcentos: 'Pincel p/ cosmeticos', dimensions: '(12 x 2,2 cm)' },
{ codigo: '141832', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '141834', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '141836', caption: 'Canivete c/ 4 funções', captionSemAcentos: 'Canivete c/ 4 funcoes', dimensions: '(5,5 x 2 x 0,7 cm)' },
{ codigo: '141837', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(6 x 2,5 cm)' },
{ codigo: '141837A', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(6 x 2,5 cm)' },
{ codigo: '141837S', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(6 x 2,5 cm)' },
{ codigo: '141837V', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(6 x 2,5 cm)' },
{ codigo: '141838', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(6 x 3,5 cm)' },
{ codigo: '141838A', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(6 x 3,5 cm)' },
{ codigo: '141838S', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(6 x 3,5 cm)' },
{ codigo: '141838V', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(6 x 3,5 cm)' },
{ codigo: '141840', caption: 'Canivete c/ 4 funções', captionSemAcentos: 'Canivete c/ 4 funcoes', dimensions: '(8,5 x 3 cm)' },
{ codigo: '141851', caption: 'Kit manicure c/ 11 pçs e estojo', captionSemAcentos: 'Kit manicure c/ 11 pcs e estojo', dimensions: '(15,5 x 11 x 2,5 cm)' },
{ codigo: '141851S', caption: 'Kit manicure c/ 11 pçs e estojo', captionSemAcentos: 'Kit manicure c/ 11 pcs e estojo', dimensions: '(15,5 x 11 x 2,5 cm)' },
{ codigo: '141851V', caption: 'Kit manicure c/ 11 pçs e estojo', captionSemAcentos: 'Kit manicure c/ 11 pcs e estojo', dimensions: '(15,5 x 11 x 2,5 cm)' },
{ codigo: '141854A', caption: 'Bloco p/ anotação (azul)', captionSemAcentos: 'Bloco p/ anotacao (azul)', dimensions: '(9 x 9 x 2,7 cm)' },
{ codigo: '141854P', caption: 'Bloco p/ anotação (preto)', captionSemAcentos: 'Bloco p/ anotacao (preto)', dimensions: '(9 x 9 x 2,7 cm)' },
{ codigo: '141856', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(7,5 x 3 cm)' },
{ codigo: '141859', caption: 'Mini kit costura', captionSemAcentos: 'Mini kit costura', dimensions: '(7,5 x 5 x 1 cm)' },
{ codigo: '141861', caption: 'Espelho c/ escova e kit costura', captionSemAcentos: 'Espelho c/ escova e kit costura', dimensions: '(14 x 8 cm)' },
{ codigo: '141864', caption: 'Lanterna de plástico recarregável', captionSemAcentos: 'Lanterna de plastico recarregavel', dimensions: '(10 x 5 x 2,5 cm)' },
{ codigo: '141864A', caption: 'Lanterna de plástico recarregável', captionSemAcentos: 'Lanterna de plastico recarregavel', dimensions: '(10 x 5 x 2,5 cm)' },
{ codigo: '141864C', caption: 'Lanterna de plástico recarregável', captionSemAcentos: 'Lanterna de plastico recarregavel', dimensions: '(10 x 5 x 2,5 cm)' },
{ codigo: '141864V', caption: 'Lanterna de plástico recarregável', captionSemAcentos: 'Lanterna de plastico recarregavel', dimensions: '(10 x 5 x 2,5 cm)' },
{ codigo: '141867', caption: 'Canivete com talheres', captionSemAcentos: 'Canivete com talheres', dimensions: '(11 x 4 x 3 cm)' },
{ codigo: '141868', caption: 'Kit churrasco c/ 8 pçs', captionSemAcentos: 'Kit churrasco c/ 8 pcs', dimensions: '(60 x 42 cm)' },
{ codigo: '141868C', caption: 'Kit churrasco c/ 8 pçs', captionSemAcentos: 'Kit churrasco c/ 8 pcs', dimensions: '(60 x 42 cm)' },
{ codigo: '141869', caption: 'Kit churrasco c/ 4 pçs', captionSemAcentos: 'Kit churrasco c/ 4 pcs', dimensions: '(38 x 11 x 7 cm)' },
{ codigo: '141872', caption: 'Lanterna de plástico recarregável', captionSemAcentos: 'Lanterna de plastico recarregavel', dimensions: '(10 x 5 x 2,5 cm)' },
{ codigo: '141873D', caption: 'Kit pincéis c/ 5 pçs', captionSemAcentos: 'Kit pinceis c/ 5 pcs', dimensions: '(20 x 5 cm)' },
{ codigo: '141876C', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(9 x 3,5 cm)' },
{ codigo: '141876P', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(9 x 3,5 cm)' },
{ codigo: '141878', caption: 'Porta foto de alumínio 10x15 cm', captionSemAcentos: 'Porta foto de aluminio 10x15 cm', dimensions: '(15 x 10 cm)' },
{ codigo: '141883B', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '141883P', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '141883V', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '141884A', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '141884G', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '141884T', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '141884V', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(11,5 x 11,5 x 8,5 cm)' },
{ codigo: '141887A', caption: 'Kit queijo c/ 5 pçs', captionSemAcentos: 'Kit queijo c/ 5 pcs', dimensions: '(33,5 x 13 x 3,5 cm)' },
{ codigo: '141889', caption: 'Kit churrasco c/ 3 pçs', captionSemAcentos: 'Kit churrasco c/ 3 pcs', dimensions: '(37 x 10 x 8 cm)' },
{ codigo: '141890P', caption: 'Kit churrasco c/ 4 pçs', captionSemAcentos: 'Kit churrasco c/ 4 pcs', dimensions: '(39 x 13,5 x 4,5 cm)' },
{ codigo: '141891P', caption: 'Kit vinho c/ 5 pçs e estojo', captionSemAcentos: 'Kit vinho c/ 5 pcs e estojo', dimensions: '(21 x 15 x 5 cm)' },
{ codigo: '141892P', caption: 'Kit vinho c/ 4 pçs e estojo', captionSemAcentos: 'Kit vinho c/ 4 pcs e estojo', dimensions: '(17,5 x 15 x 5 cm)' },
{ codigo: '141893', caption: 'Porta foto de acrílico 10x14 cm', captionSemAcentos: 'Porta foto de acrilico 10x14 cm', dimensions: '(10 x 14 cm)' },
{ codigo: '141899', caption: 'Moedor de pimenta manual', captionSemAcentos: 'Moedor de pimenta manual', dimensions: '(14 x 4,5 cm)' },
{ codigo: '141900', caption: 'Moedor de pimenta manual', captionSemAcentos: 'Moedor de pimenta manual', dimensions: '(21,5 x 5 cm)' },
{ codigo: '143002A', caption: 'Kit queijo c/ 3 pçs', captionSemAcentos: 'Kit queijo c/ 3 pcs', dimensions: '(16 x 12,5 x 3,5 cm)' },
{ codigo: '143004C', caption: 'Kit churrasco c/ 3 pçs', captionSemAcentos: 'Kit churrasco c/ 3 pcs', dimensions: '(45 x 15 cm)' },
{ codigo: '143004P', caption: 'Kit churrasco c/ 3 pçs', captionSemAcentos: 'Kit churrasco c/ 3 pcs', dimensions: '(45 x 15 cm)' },
{ codigo: '143005', caption: 'Relógio digital c/ prendedor', captionSemAcentos: 'Relogio digital c/ prendedor', dimensions: '(8,5 x 5,5 x 2,5 cm)' },
{ codigo: '143007', caption: 'Kit costura c/ estojo', captionSemAcentos: 'Kit costura c/ estojo', dimensions: '(12,5 x 10 x 3 cm)' },
{ codigo: '143008', caption: 'Kit costura c/ estojo', captionSemAcentos: 'Kit costura c/ estojo', dimensions: '(17 x 8,5 x 2,5 cm)' },
{ codigo: '143013', caption: 'Canivete c/ 4 funções', captionSemAcentos: 'Canivete c/ 4 funcoes', dimensions: '(7 x 2 x 2 cm)' },
{ codigo: '143014R', caption: 'Kit manicure c/ 3 pçs', captionSemAcentos: 'Kit manicure c/ 3 pcs', dimensions: '(7,5 x 4,5 x 2 cm)' },
{ codigo: '143016', caption: 'Lupa plástica c/ luz', captionSemAcentos: 'Lupa plastica c/ luz', dimensions: '(9 x 5,5 x 1 cm)' },
{ codigo: '143019', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(7,5 x 3 cm)' },
{ codigo: '143020A', caption: 'Chaveiro plástico c/ luz', captionSemAcentos: 'Chaveiro plastico c/ luz', dimensions: '(7,5 x 4 cm)' },
{ codigo: '143020P', caption: 'Chaveiro plástico c/ luz', captionSemAcentos: 'Chaveiro plastico c/ luz', dimensions: '(7,5 x 4 cm)' },
{ codigo: '143020V', caption: 'Chaveiro plástico c/ luz', captionSemAcentos: 'Chaveiro plastico c/ luz', dimensions: '(7,5 x 4 cm)' },
{ codigo: '143021A', caption: 'Chaveiro plástico c/ luz', captionSemAcentos: 'Chaveiro plastico c/ luz', dimensions: '(7,5 x 4 cm)' },
{ codigo: '143021P', caption: 'Chaveiro plástico c/ luz', captionSemAcentos: 'Chaveiro plastico c/ luz', dimensions: '(7,5 x 4 cm)' },
{ codigo: '143021V', caption: 'Chaveiro plástico c/ luz', captionSemAcentos: 'Chaveiro plastico c/ luz', dimensions: '(7,5 x 4 cm)' },
{ codigo: '143024', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '143025', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '143026', caption: 'Moedor de pimenta de metal', captionSemAcentos: 'Moedor de pimenta de metal', dimensions: '(11,8 x 5,3 cm)' },
{ codigo: '143027', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(20 x 6,5 cm)' },
{ codigo: '143027A', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(20 x 6,5 cm)' },
{ codigo: '143027V', caption: 'Squeeze de inox 500 ml', captionSemAcentos: 'Squeeze de inox 500 ml', dimensions: '(20 x 6,5 cm)' },
{ codigo: '143028', caption: 'Kit caneta e lapiseira com chaveiro e porta cartão', captionSemAcentos: 'Kit caneta e lapiseira com chaveiro e porta cartao', dimensions: '(19,5 x 17 cm)' },
{ codigo: '143029', caption: 'Jogo de ferramentas c/ 4 pçs', captionSemAcentos: 'Jogo de ferramentas c/ 4 pcs', dimensions: '(10,5 x 1,5 x 1,5 cm)' },
{ codigo: '143030', caption: 'Jogo de ferramentas c/ lanterna e chaveiro', captionSemAcentos: 'Jogo de ferramentas c/ lanterna e chaveiro', dimensions: '(7 x 2 x 2 cm)' },
{ codigo: '143035', caption: 'Kit churrasco c/ 2 pçs', captionSemAcentos: 'Kit churrasco c/ 2 pcs', dimensions: '(36 x 9,5 x 3 cm)' },
{ codigo: '143035P', caption: 'Kit churrasco c/ 2 pçs', captionSemAcentos: 'Kit churrasco c/ 2 pcs', dimensions: '(36 x 9,5 x 3 cm)' },
{ codigo: '143036', caption: 'Kit churrasco c/ 4 pçs', captionSemAcentos: 'Kit churrasco c/ 4 pcs', dimensions: '(43 x 15,5 x 6 cm)' },
{ codigo: '143037', caption: 'Kit churrasco c/ 4 pçs', captionSemAcentos: 'Kit churrasco c/ 4 pcs', dimensions: '(49 x 15,5 x 6 cm)' },
{ codigo: '143038', caption: 'Caneca de inox 180 ml', captionSemAcentos: 'Caneca de inox 180 ml', dimensions: '(10 x 8 x 7 cm)' },
{ codigo: '143039A', caption: 'Kit queijo c/ 4 pçs', captionSemAcentos: 'Kit queijo c/ 4 pcs', dimensions: '(20,5 x 19 x 3 cm)' },
{ codigo: '143040', caption: 'Cantil de inox 350 ml', captionSemAcentos: 'Cantil de inox 350 ml', dimensions: '(19,5 x 7 cm)' },
{ codigo: '143042', caption: 'Porta copo de inox', captionSemAcentos: 'Porta copo de inox', dimensions: '(13 x 6 cm)' },
{ codigo: '143045', caption: 'Relógio digital plástico', captionSemAcentos: 'Relogio digital plastico', dimensions: '(10,5 x 3 x 3 cm)' },
{ codigo: '143046', caption: 'Lupa de plástico c/ capa', captionSemAcentos: 'Lupa de plastico c/ capa', dimensions: '(8,5 x 6,5 cm)' },
{ codigo: '143049', caption: 'Lupa 90mm c/ luz', captionSemAcentos: 'Lupa 90mm c/ luz', dimensions: '(23,5 x 11 x 2 cm)' },
{ codigo: '143058', caption: 'Lanterna c/ kit ferramentas', captionSemAcentos: 'Lanterna c/ kit ferramentas', dimensions: '(19 x 12 x 9 cm)' },
{ codigo: '143059', caption: 'Kit vinho c/ 4 pçs', captionSemAcentos: 'Kit vinho c/ 4 pcs', dimensions: '(16,5 x 13 x 2,5 cm)' },
{ codigo: '143060', caption: 'Kit vinho c/ 4 pçs', captionSemAcentos: 'Kit vinho c/ 4 pcs', dimensions: '(17 x 11,5 x 2,5 cm)' },
{ codigo: '143061P', caption: 'Kit manicure c/ 6 pçs', captionSemAcentos: 'Kit manicure c/ 6 pcs', dimensions: '(10 x 5,5 x 2,5 cm)' },
{ codigo: '143062', caption: 'Kit vinho c/ 2 pçs', captionSemAcentos: 'Kit vinho c/ 2 pcs', dimensions: '(11 x 11 x 2,5 cm)' },
{ codigo: '143064', caption: 'Jogo de talheres dobráveis', captionSemAcentos: 'Jogo de talheres dobraveis', dimensions: '(12 x 7,5 cm)' },
{ codigo: '143066', caption: 'Mini luminária p/ leitura c/ clip', captionSemAcentos: 'Mini luminaria p/ leitura c/ clip', dimensions: '(19 x 8 cm)' },
{ codigo: '143067', caption: 'Mini luminária p/ leitura c/ clip', captionSemAcentos: 'Mini luminaria p/ leitura c/ clip', dimensions: '(19 x 8 cm)' },
{ codigo: '143069B', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '143069R', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(7 x 3,5 cm)' },
{ codigo: '143070', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(7 x 3,5 cm)' },
{ codigo: '143072', caption: 'Mini lâmpada p/ leitura c/ clip', captionSemAcentos: 'Mini lampada p/ leitura c/ clip', dimensions: '(25 x 2,5 x 2,5 cm)' },
{ codigo: '143076', caption: 'Lupa de plástico c/ capa', captionSemAcentos: 'Lupa de plastico c/ capa', dimensions: '(5,5 x 5,5 cm)' },
{ codigo: '143077', caption: 'Porta caneta c/ bloco p/ anotação', captionSemAcentos: 'Porta caneta c/ bloco p/ anotacao', dimensions: '(13 x 10,5 x 2 cm)' },
{ codigo: '143078', caption: 'Porta caneta c/ bloco p/ anotação', captionSemAcentos: 'Porta caneta c/ bloco p/ anotacao', dimensions: '(18 x 10,5 x 2 cm)' },
{ codigo: '143079', caption: 'Lupa de plástico c/ capa', captionSemAcentos: 'Lupa de plastico c/ capa', dimensions: '(8,5 x 6,5 x 1,8 cm)' },
{ codigo: '143083', caption: 'Kit vinho c/ 4 pçs', captionSemAcentos: 'Kit vinho c/ 4 pcs', dimensions: '(17 x 11,5 cm)' },
{ codigo: '143084', caption: 'Kit vinho c/ 4 pçs', captionSemAcentos: 'Kit vinho c/ 4 pcs', dimensions: '(17 x 13 cm)' },
{ codigo: '143085A', caption: 'Jogo de ferramentas c/ 6 pçs', captionSemAcentos: 'Jogo de ferramentas c/ 6 pcs', dimensions: '(10 x 3 x 1,8 cm)' },
{ codigo: '143085P', caption: 'Jogo de ferramentas c/ 6 pçs', captionSemAcentos: 'Jogo de ferramentas c/ 6 pcs', dimensions: '(10 x 3 x 1,8 cm)' },
{ codigo: '143085V', caption: 'Jogo de ferramentas c/ 6 pçs', captionSemAcentos: 'Jogo de ferramentas c/ 6 pcs', dimensions: '(10 x 3 x 1,8 cm)' },
{ codigo: '143086', caption: 'Gancho de metal p/ bolsas', captionSemAcentos: 'Gancho de metal p/ bolsas', dimensions: '(11 x 7 cm)' },
{ codigo: '143086P', caption: 'Gancho de metal p/ bolsas', captionSemAcentos: 'Gancho de metal p/ bolsas', dimensions: '(11 x 7 cm)' },
{ codigo: '143087', caption: 'Gancho de metal p/ bolsas', captionSemAcentos: 'Gancho de metal p/ bolsas', dimensions: '(4,5 cm)' },
{ codigo: '143088', caption: 'Gancho de metal p/ bolsas', captionSemAcentos: 'Gancho de metal p/ bolsas', dimensions: '(4,5 cm)' },
{ codigo: '143091A', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(12 x 11,5 x 8,5 cm)' },
{ codigo: '143091C', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(12 x 11,5 x 8,5 cm)' },
{ codigo: '143091T', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(12 x 11,5 x 8,5 cm)' },
{ codigo: '143091V', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(12 x 11,5 x 8,5 cm)' },
{ codigo: '143092', caption: 'Jogo de facas p/ cozinha c/ estojo', captionSemAcentos: 'Jogo de facas p/ cozinha c/ estojo', dimensions: '(36,5 x 26 x 3,5 cm)' },
{ codigo: '143093A', caption: 'Jogo de facas p/ cozinha c/ suporte', captionSemAcentos: 'Jogo de facas p/ cozinha c/ suporte', dimensions: '(34 x 29 x 9 cm)' },
{ codigo: '143093G', caption: 'Jogo de facas p/ cozinha c/ suporte', captionSemAcentos: 'Jogo de facas p/ cozinha c/ suporte', dimensions: '(34 x 29 x 9 cm)' },
{ codigo: '143094A', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(14,5 x 12 x 3,5 cm)' },
{ codigo: '143094T', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(14,5 x 12 x 3,5 cm)' },
{ codigo: '143094V', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(14,5 x 12 x 3,5 cm)' },
{ codigo: '143098', caption: 'Cortador de unha c/ chaveiro', captionSemAcentos: 'Cortador de unha c/ chaveiro', dimensions: '(5,5 x 3,2 cm)' },
{ codigo: '143099', caption: 'Saca rolhas c/ abridor e canivete', captionSemAcentos: 'Saca rolhas c/ abridor e canivete', dimensions: '(12 x 2,5 x 1,2 cm)' },
{ codigo: '143099A', caption: 'Saca rolhas c/ abridor e canivete', captionSemAcentos: 'Saca rolhas c/ abridor e canivete', dimensions: '(12 x 2,5 x 1,2 cm)' },
{ codigo: '143099V', caption: 'Saca rolhas c/ abridor e canivete', captionSemAcentos: 'Saca rolhas c/ abridor e canivete', dimensions: '(12 x 2,5 x 1,2 cm)' },
{ codigo: '143102', caption: 'Relógio plástico c/ calculadora', captionSemAcentos: 'Relogio plastico c/ calculadora', dimensions: '(10 x 2,3 x 5,7 cm)' },
{ codigo: '143104', caption: 'Gancho de metal p/ bolsas', captionSemAcentos: 'Gancho de metal p/ bolsas', dimensions: '(11 x 7 cm)' },
{ codigo: '143104P', caption: 'Gancho de metal p/ bolsas', captionSemAcentos: 'Gancho de metal p/ bolsas', dimensions: '(11 x 7 cm)' },
{ codigo: '143105', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8,5 x 4,5 cm)' },
{ codigo: '143106A', caption: 'Tampa de metal p/ garrafa', captionSemAcentos: 'Tampa de metal p/ garrafa', dimensions: '(9 x 2 cm)' },
{ codigo: '143107C', caption: 'Kit churrasco c/ 5 pçs', captionSemAcentos: 'Kit churrasco c/ 5 pcs', dimensions: '(60 x 42 cm)' },
{ codigo: '143107G', caption: 'Kit churrasco c/ 5 pçs', captionSemAcentos: 'Kit churrasco c/ 5 pcs', dimensions: '(60 x 42 cm)' },
{ codigo: '143107P', caption: 'Kit churrasco c/ 5 pçs', captionSemAcentos: 'Kit churrasco c/ 5 pcs', dimensions: '(60 x 42 cm)' },
{ codigo: '143108', caption: 'Abridor de carta de metal', captionSemAcentos: 'Abridor de carta de metal', dimensions: '(14 x 2,5 cm)' },
{ codigo: '143109', caption: 'Necessaire de plástico', captionSemAcentos: 'Necessaire de plastico', dimensions: '(16 x 9 x 6 cm)' },
{ codigo: '143110C', caption: 'Necessaire de plástico', captionSemAcentos: 'Necessaire de plastico', dimensions: '(20 x 10 x 6,5 cm)' },
{ codigo: '143110R', caption: 'Necessaire de plástico', captionSemAcentos: 'Necessaire de plastico', dimensions: '(20 x 10 x 6,5 cm)' },
{ codigo: '143113', caption: 'Balança p/ bagagem', captionSemAcentos: 'Balanca p/ bagagem', dimensions: '(20 x 7 x 2,3 cm)' },
{ codigo: '143116T', caption: 'Caneca plástica 400 ml', captionSemAcentos: 'Caneca plastica 400 ml', dimensions: '(15,5 x 8 cm)' },
{ codigo: '143117', caption: 'Porta copos de inox', captionSemAcentos: 'Porta copos de inox', dimensions: '(10 x 3,5 cm)' },
{ codigo: '143118', caption: 'Porta copos de inox', captionSemAcentos: 'Porta copos de inox', dimensions: '(9,5 x 3,5 cm)' },
{ codigo: '143121', caption: 'Chaveiro abridor de garrafa', captionSemAcentos: 'Chaveiro abridor de garrafa', dimensions: '(8,5 x 1 x 1,5 cm)' },
{ codigo: '143122', caption: 'Kit ferramentas c/ estojo', captionSemAcentos: 'Kit ferramentas c/ estojo', dimensions: '(18 x 10 x 4 cm)' },
{ codigo: '143123A', caption: 'Canivete c/ bússola', captionSemAcentos: 'Canivete c/ bussola', dimensions: '(9 x 3 x 2,3 cm)' },
{ codigo: '143123P', caption: 'Canivete c/ bússola', captionSemAcentos: 'Canivete c/ bussola', dimensions: '(9 x 3 x 2,3 cm)' },
{ codigo: '143124', caption: 'Ferramenta de inox c/ 11 funções', captionSemAcentos: 'Ferramenta de inox c/ 11 funcoes', dimensions: '(7 x 4,5 cm)' },
{ codigo: '143126P', caption: 'Mini balança', captionSemAcentos: 'Mini balanca', dimensions: '(23 x 13 x 2 cm)' },
{ codigo: '143127', caption: 'Espelho de bolso duplo', captionSemAcentos: 'Espelho de bolso duplo', dimensions: '(6,5 x 6,5 x 0,7 cm)' },
{ codigo: '143128', caption: 'Kit manicure c/ 5 pçs', captionSemAcentos: 'Kit manicure c/ 5 pcs', dimensions: '(10,5 x 4,5 x 3 cm)' },
{ codigo: '143129', caption: 'Jogo de facas c/ 5 pçs', captionSemAcentos: 'Jogo de facas c/ 5 pcs', dimensions: '(36 x 25 x 3,5 cm)' },
{ codigo: '143130A', caption: 'Jogo de ferramentas c/ 6 pçs', captionSemAcentos: 'Jogo de ferramentas c/ 6 pcs', dimensions: '(10 x 3,5 x 1,8 cm)' },
{ codigo: '143130C', caption: 'Jogo de ferramentas c/ 6 pçs', captionSemAcentos: 'Jogo de ferramentas c/ 6 pcs', dimensions: '(10 x 3,5 x 1,8 cm)' },
{ codigo: '143130V', caption: 'Jogo de ferramentas c/ 6 pçs', captionSemAcentos: 'Jogo de ferramentas c/ 6 pcs', dimensions: '(10 x 3,5 x 1,8 cm)' },
{ codigo: '143131', caption: 'Espelho de bolso duplo', captionSemAcentos: 'Espelho de bolso duplo', dimensions: '(7 cm)' },
{ codigo: '143132A', caption: 'Bloco p/ anotação c/ refil', captionSemAcentos: 'Bloco p/ anotacao c/ refil', dimensions: '(12 x 7,5 cm)' },
{ codigo: '143132C', caption: 'Bloco p/ anotação c/ refil', captionSemAcentos: 'Bloco p/ anotacao c/ refil', dimensions: '(12 x 7,5 cm)' },
{ codigo: '143132P', caption: 'Bloco p/ anotação c/ refil', captionSemAcentos: 'Bloco p/ anotacao c/ refil', dimensions: '(12 x 7,5 cm)' },
{ codigo: '143132V', caption: 'Bloco p/ anotação c/ refil', captionSemAcentos: 'Bloco p/ anotacao c/ refil', dimensions: '(12 x 7,5 cm)' },
{ codigo: '143133', caption: 'Kit churrasco c/ 6 pçs', captionSemAcentos: 'Kit churrasco c/ 6 pcs', dimensions: '(36 x 15 x 2,5 cm)' },
{ codigo: '143134', caption: 'Kit churrasco c/ 7 pçs', captionSemAcentos: 'Kit churrasco c/ 7 pcs', dimensions: '(36 x 15,5 x 3 cm)' },
{ codigo: '143135', caption: 'Kit churrasco c/ 8 pçs', captionSemAcentos: 'Kit churrasco c/ 8 pcs', dimensions: '(36 x 24 x 4 cm)' },
{ codigo: '143136', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(8,5 x 3,5 cm)' },
{ codigo: '143137', caption: 'Relógio c/ porta foto e porta canetas', captionSemAcentos: 'Relogio c/ porta foto e porta canetas', dimensions: '(14 x 14 x 3 cm)' },
{ codigo: '143138A', caption: 'Mini lanterna manual', captionSemAcentos: 'Mini lanterna manual', dimensions: '(9,5 x 2 cm)' },
{ codigo: '143138P', caption: 'Mini lanterna manual', captionSemAcentos: 'Mini lanterna manual', dimensions: '(9,5 x 2 cm)' },
{ codigo: '143138S', caption: 'Mini lanterna manual', captionSemAcentos: 'Mini lanterna manual', dimensions: '(9,5 x 2 cm)' },
{ codigo: '143138V', caption: 'Mini lanterna manual', captionSemAcentos: 'Mini lanterna manual', dimensions: '(9,5 x 2 cm)' },
{ codigo: '143139A', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(4 x 2,7 cm)' },
{ codigo: '143139P', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(4 x 2,7 cm)' },
{ codigo: '143139S', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(4 x 2,7 cm)' },
{ codigo: '143139V', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(4 x 2,7 cm)' },
{ codigo: '143140A', caption: 'Mini lanterna manual c/ mosquetão', captionSemAcentos: 'Mini lanterna manual c/ mosquetao', dimensions: '(5,5 x 1,5 cm)' },
{ codigo: '143140P', caption: 'Mini lanterna manual c/ mosquetão', captionSemAcentos: 'Mini lanterna manual c/ mosquetao', dimensions: '(5,5 x 1,5 cm)' },
{ codigo: '143140S', caption: 'Mini lanterna manual c/ mosquetão', captionSemAcentos: 'Mini lanterna manual c/ mosquetao', dimensions: '(5,5 x 1,5 cm)' },
{ codigo: '143140V', caption: 'Mini lanterna manual c/ mosquetão', captionSemAcentos: 'Mini lanterna manual c/ mosquetao', dimensions: '(5,5 x 1,5 cm)' },
{ codigo: '143142P', caption: 'Mouse pad c/ calculadora', captionSemAcentos: 'Mouse pad c/ calculadora', dimensions: '(27 x 20,5 x 1,7 cm)' },
{ codigo: '143143A', caption: 'Squeeze plástico 450 ml', captionSemAcentos: 'Squeeze plastico 450 ml', dimensions: '(20 x 6 cm)' },
{ codigo: '143143G', caption: 'Squeeze plástico 450 ml', captionSemAcentos: 'Squeeze plastico 450 ml', dimensions: '(20 x 6 cm)' },
{ codigo: '143143P', caption: 'Squeeze plástico 450 ml', captionSemAcentos: 'Squeeze plastico 450 ml', dimensions: '(20 x 6 cm)' },
{ codigo: '143143V', caption: 'Squeeze plástico 450 ml', captionSemAcentos: 'Squeeze plastico 450 ml', dimensions: '(20 x 6 cm)' },
{ codigo: '143144', caption: 'Kit queijo c/ 4 pçs', captionSemAcentos: 'Kit queijo c/ 4 pcs', dimensions: '(19 x 16,5 x 2 cm)' },
{ codigo: '143145', caption: 'Kit queijo c/ 5 pçs', captionSemAcentos: 'Kit queijo c/ 5 pcs', dimensions: '(23 x 5 cm)' },
{ codigo: '143146', caption: 'Moedor de pimenta manual', captionSemAcentos: 'Moedor de pimenta manual', dimensions: '(14 x 9 x 4,5 cm)' },
{ codigo: '143147A', caption: 'Squeeze de inox 600 ml', captionSemAcentos: 'Squeeze de inox 600 ml', dimensions: '(24 x 7 cm)' },
{ codigo: '143147G', caption: 'Squeeze de inox 600 ml', captionSemAcentos: 'Squeeze de inox 600 ml', dimensions: '(24 x 7 cm)' },
{ codigo: '143147P', caption: 'Squeeze de inox 600 ml', captionSemAcentos: 'Squeeze de inox 600 ml', dimensions: '(24 x 7 cm)' },
{ codigo: '143147V', caption: 'Squeeze de inox 600 ml', captionSemAcentos: 'Squeeze de inox 600 ml', dimensions: '(24 x 7 cm)' },
{ codigo: '143148', caption: 'Mosquetão de alumínio', captionSemAcentos: 'Mosquetao de aluminio', dimensions: '(8 x 4 cm)' },
{ codigo: '143149', caption: 'Mosquetão de alumínio', captionSemAcentos: 'Mosquetao de aluminio', dimensions: '(6,5 x 3,3 cm)' },
{ codigo: '143150', caption: 'Lanterna c/ kit ferramentas', captionSemAcentos: 'Lanterna c/ kit ferramentas', dimensions: '(19,5 x 12,5 x 4,5 cm)' },
{ codigo: '143151A', caption: 'Mini chave de fenda e estojo', captionSemAcentos: 'Mini chave de fenda e estojo', dimensions: '(7 x 2,5 x 1,5 cm)' },
{ codigo: '143151P', caption: 'Mini chave de fenda e estojo', captionSemAcentos: 'Mini chave de fenda e estojo', dimensions: '(7 x 2,5 x 1,5 cm)' },
{ codigo: '143151V', caption: 'Mini chave de fenda e estojo', captionSemAcentos: 'Mini chave de fenda e estojo', dimensions: '(7 x 2,5 x 1,5 cm)' },
{ codigo: '143152', caption: 'Lanterna c/ kit ferramentas', captionSemAcentos: 'Lanterna c/ kit ferramentas', dimensions: '(19,5 x 13,5 x 7 cm)' },
{ codigo: '143153', caption: 'Binóculos', captionSemAcentos: 'Binoculos', dimensions: '(11 x 11 x 3 cm)' },
{ codigo: '143155', caption: 'Kit manicure c/ 10 pçs', captionSemAcentos: 'Kit manicure c/ 10 pcs', dimensions: '(15,5 x 10,5 x 2,5 cm)' },
{ codigo: '143156', caption: 'Chaveiro c/ canivete c/ 4 funções', captionSemAcentos: 'Chaveiro c/ canivete c/ 4 funcoes', dimensions: '(9,5 x 3 cm)' },
{ codigo: '143157', caption: 'Chaveiro c/ canivete c/ 4 funções', captionSemAcentos: 'Chaveiro c/ canivete c/ 4 funcoes', dimensions: '(9,5 x 3 cm)' },
{ codigo: '143158B', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(7 x 3 cm)' },
{ codigo: '143158R', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(7 x 3 cm)' },
{ codigo: '143159A', caption: 'Estojo c/ bloco p/ anotação', captionSemAcentos: 'Estojo c/ bloco p/ anotacao', dimensions: '(13 x 11,5 x 1,5 cm)' },
{ codigo: '143159B', caption: 'Estojo c/ bloco p/ anotação', captionSemAcentos: 'Estojo c/ bloco p/ anotacao', dimensions: '(13 x 11,5 x 1,5 cm)' },
{ codigo: '143159C', caption: 'Estojo c/ bloco p/ anotação', captionSemAcentos: 'Estojo c/ bloco p/ anotacao', dimensions: '(13 x 11,5 x 1,5 cm)' },
{ codigo: '143159L', caption: 'Estojo c/ bloco p/ anotação', captionSemAcentos: 'Estojo c/ bloco p/ anotacao', dimensions: '(13 x 11,5 x 1,5 cm)' },
{ codigo: '143159P', caption: 'Estojo c/ bloco p/ anotação', captionSemAcentos: 'Estojo c/ bloco p/ anotacao', dimensions: '(13 x 11,5 x 1,5 cm)' },
{ codigo: '143159V', caption: 'Estojo c/ bloco p/ anotação', captionSemAcentos: 'Estojo c/ bloco p/ anotacao', dimensions: '(13 x 11,5 x 1,5 cm)' },
{ codigo: '143160', caption: 'Bloco p/ anotação', captionSemAcentos: 'Bloco p/ anotacao', dimensions: '(9 x 9 x 2 cm)' },
{ codigo: '143161', caption: 'Bloco p/ anotação', captionSemAcentos: 'Bloco p/ anotacao', dimensions: '(13 x 9 cm)' },
{ codigo: '143162', caption: 'Porta cartão de metal', captionSemAcentos: 'Porta cartao de metal', dimensions: '(9,5 x 6 x 0,7 cm)' },
{ codigo: '143163M', caption: 'Porta cartão de couro sintético', captionSemAcentos: 'Porta cartao de couro sintetico', dimensions: '(9,5 x 6 cm)' },
{ codigo: '143163P', caption: 'Porta cartão de couro sintético', captionSemAcentos: 'Porta cartao de couro sintetico', dimensions: '(9,5 x 6 cm)' },
{ codigo: '143164P', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(9,5 x 3 cm)' },
{ codigo: '143165A', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(8,5 x 3,5 cm)' },
{ codigo: '143165I', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(8,5 x 3,5 cm)' },
{ codigo: '143170A', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '143170G', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '143170L', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '143170P', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '143170V', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '143171A', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(8,5 x 4 cm)' },
{ codigo: '143171L', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(8,5 x 4 cm)' },
{ codigo: '143171V', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(8,5 x 4 cm)' },
{ codigo: '143172', caption: 'Saca rolhas de metal', captionSemAcentos: 'Saca rolhas de metal', dimensions: '(12 x 2 x 1,2 cm)' },
{ codigo: '143173', caption: 'Calculadora eletrônica', captionSemAcentos: 'Calculadora eletronica', dimensions: '(10 x 6 cm)' },
{ codigo: '143174', caption: 'Calculadora eletrônica', captionSemAcentos: 'Calculadora eletronica', dimensions: '(10 x 6 cm)' },
{ codigo: '143175', caption: 'Luz de LED p/ notebook', captionSemAcentos: 'Luz de LED p/ notebook', dimensions: '(42 x 2,5 cm)' },
{ codigo: '143176A', caption: 'Squeeze plástico dobrável 450 ml', captionSemAcentos: 'Squeeze plastico dobravel 450 ml', dimensions: '(26 x 12 cm)' },
{ codigo: '143176B', caption: 'Squeeze plástico dobrável 450 ml', captionSemAcentos: 'Squeeze plastico dobravel 450 ml', dimensions: '(26 x 12 cm)' },
{ codigo: '143176C', caption: 'Squeeze plástico dobrável 450 ml', captionSemAcentos: 'Squeeze plastico dobravel 450 ml', dimensions: '(26 x 12 cm)' },
{ codigo: '143176G', caption: 'Squeeze plástico dobrável 450 ml', captionSemAcentos: 'Squeeze plastico dobravel 450 ml', dimensions: '(26 x 12 cm)' },
{ codigo: '143176GG', caption: 'Squeeze plástico dobrável 450 ml', captionSemAcentos: 'Squeeze plastico dobravel 450 ml', dimensions: '(26 x 12 cm)' },
{ codigo: '143176L', caption: 'Squeeze plástico dobrável 450 ml', captionSemAcentos: 'Squeeze plastico dobravel 450 ml', dimensions: '(26 x 12 cm)' },
{ codigo: '143176P', caption: 'Squeeze plástico dobrável 450 ml', captionSemAcentos: 'Squeeze plastico dobravel 450 ml', dimensions: '(26 x 12 cm)' },
{ codigo: '143176R', caption: 'Squeeze plástico dobrável 450 ml', captionSemAcentos: 'Squeeze plastico dobravel 450 ml', dimensions: '(26 x 12 cm)' },
{ codigo: '143176V', caption: 'Squeeze plástico dobrável 450 ml', captionSemAcentos: 'Squeeze plastico dobravel 450 ml', dimensions: '(26 x 12 cm)' },
{ codigo: '143176Y', caption: 'Squeeze plástico dobrável 450 ml', captionSemAcentos: 'Squeeze plastico dobravel 450 ml', dimensions: '(26 x 12 cm)' },
{ codigo: '143178', caption: 'Kit queijo c/ 3 pçs', captionSemAcentos: 'Kit queijo c/ 3 pcs', dimensions: '(14 x 8 cm)' },
{ codigo: '143179', caption: 'Chaveiro de metal giratório', captionSemAcentos: 'Chaveiro de metal giratorio', dimensions: '(7 x 3,5 cm)' },
{ codigo: '143180', caption: 'Bico dosador p/ garrafa', captionSemAcentos: 'Bico dosador p/ garrafa', dimensions: '(7,5 x 2 cm)' },
{ codigo: '143181', caption: 'Chaveiro de metal c/ cortador de unha', captionSemAcentos: 'Chaveiro de metal c/ cortador de unha', dimensions: '(9 x 3 cm)' },
{ codigo: '143182A', caption: 'Lanterna c/ jogo de ferramentas', captionSemAcentos: 'Lanterna c/ jogo de ferramentas', dimensions: '(9,3 x 3,5 x 1,3 cm)' },
{ codigo: '143182P', caption: 'Lanterna c/ jogo de ferramentas', captionSemAcentos: 'Lanterna c/ jogo de ferramentas', dimensions: '(9,3 x 3,5 x 1,3 cm)' },
{ codigo: '143182V', caption: 'Lanterna c/ jogo de ferramentas', captionSemAcentos: 'Lanterna c/ jogo de ferramentas', dimensions: '(9,3 x 3,5 x 1,3 cm)' },
{ codigo: '143183', caption: 'Kit churrasco c/ 4 pçs', captionSemAcentos: 'Kit churrasco c/ 4 pcs', dimensions: '(38 x 11,5 x 5 cm)' },
{ codigo: '143184', caption: 'Kit churrasco c/ 3 pçs', captionSemAcentos: 'Kit churrasco c/ 3 pcs', dimensions: '(38 x 9 x 5 cm)' },
{ codigo: '143185', caption: 'Kit queijo c/ 5 pçs', captionSemAcentos: 'Kit queijo c/ 5 pcs', dimensions: '(22 x 3,5 cm)' },
{ codigo: '143186A', caption: 'Squeeze plástico com canudo 400 ml', captionSemAcentos: 'Squeeze plastico com canudo 400 ml', dimensions: '(19,5 x 7 cm)' },
{ codigo: '143186P', caption: 'Squeeze plástico com canudo 400 ml', captionSemAcentos: 'Squeeze plastico com canudo 400 ml', dimensions: '(19,5 x 7 cm)' },
{ codigo: '143186V', caption: 'Squeeze plástico com canudo 400 ml', captionSemAcentos: 'Squeeze plastico com canudo 400 ml', dimensions: '(19,5 x 7 cm)' },
{ codigo: '143187A', caption: 'Cantil 500 ml', captionSemAcentos: 'Cantil 500 ml', dimensions: '(23 x 6,5 cm)' },
{ codigo: '143187S', caption: 'Cantil 500 ml', captionSemAcentos: 'Cantil 500 ml', dimensions: '(23 x 6,5 cm)' },
{ codigo: '143187V', caption: 'Cantil 500 ml', captionSemAcentos: 'Cantil 500 ml', dimensions: '(23 x 6,5 cm)' },
{ codigo: '143188', caption: 'Espelho de bolso duplo', captionSemAcentos: 'Espelho de bolso duplo', dimensions: '(8,5 x 6 cm)' },
{ codigo: '143189', caption: 'Espelho de bolso duplo', captionSemAcentos: 'Espelho de bolso duplo', dimensions: '(8,5 x 6 x 0,8 cm)' },
{ codigo: '143190', caption: 'Kit vinho c/ 5 pçs', captionSemAcentos: 'Kit vinho c/ 5 pcs', dimensions: '(17 x 16,5 x 3 cm)' },
{ codigo: '143191B', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 2,7 cm)' },
{ codigo: '143191K', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(8 x 3 cm)' },
{ codigo: '143191R', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(7 x 3,5 cm)' },
{ codigo: '143192A', caption: 'Squeeze plástico 600 ml', captionSemAcentos: 'Squeeze plastico 600 ml', dimensions: '(24,5 x 7 cm)' },
{ codigo: '143192P', caption: 'Squeeze plástico 600 ml', captionSemAcentos: 'Squeeze plastico 600 ml', dimensions: '(24,5 x 7 cm)' },
{ codigo: '143192V', caption: 'Squeeze plástico 600 ml', captionSemAcentos: 'Squeeze plastico 600 ml', dimensions: '(24,5 x 7 cm)' },
{ codigo: '143193', caption: 'Canivete c/ 10 funções', captionSemAcentos: 'Canivete c/ 10 funcoes', dimensions: '(9,5 x 2,5 x 1,8 cm)' },
{ codigo: '143194', caption: 'Kit manicure c/ 18 pçs', captionSemAcentos: 'Kit manicure c/ 18 pcs', dimensions: '(18 x 12 x 2 cm)' },
{ codigo: '143195', caption: 'Kit manicure c/ 15 pçs', captionSemAcentos: 'Kit manicure c/ 15 pcs', dimensions: '(17 x 12,5 x 2 cm)' },
{ codigo: '143196', caption: 'Kit manicure c/ 12 pçs', captionSemAcentos: 'Kit manicure c/ 12 pcs', dimensions: '(15,5 x 10 x 2 cm)' },
{ codigo: '143197', caption: 'Vaporizador de perfume 10 ml', captionSemAcentos: 'Vaporizador de perfume 10 ml', dimensions: '(9,5 x 2,3 cm)' },
{ codigo: '143198', caption: 'Espelho de bolso duplo', captionSemAcentos: 'Espelho de bolso duplo', dimensions: '(7,3 x 6,5 cm)' },
{ codigo: '143199', caption: 'Kit churrasco c/ 18 pçs', captionSemAcentos: 'Kit churrasco c/ 18 pcs', dimensions: '(44,5 x 30,5 x 6,5 cm)' },
{ codigo: '143200A', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(9,5 x 4 cm)' },
{ codigo: '143201A', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(9 x 3,5 cm)' },
{ codigo: '143203A', caption: 'Estojo c/ bloco p/ anotação', captionSemAcentos: 'Estojo c/ bloco p/ anotacao', dimensions: '(13 x 9 x 1 cm)' },
{ codigo: '143203B', caption: 'Estojo c/ bloco p/ anotação', captionSemAcentos: 'Estojo c/ bloco p/ anotacao', dimensions: '(13 x 9 x 1 cm)' },
{ codigo: '143203C', caption: 'Estojo c/ bloco p/ anotação', captionSemAcentos: 'Estojo c/ bloco p/ anotacao', dimensions: '(13 x 9 x 1 cm)' },
{ codigo: '143203V', caption: 'Estojo c/ bloco p/ anotação', captionSemAcentos: 'Estojo c/ bloco p/ anotacao', dimensions: '(13 x 9 x 1 cm)' },
{ codigo: '143204', caption: 'Caneca de metal 180 ml', captionSemAcentos: 'Caneca de metal 180 ml', dimensions: '(9 x 10 x 6,7 cm)' },
{ codigo: '143205A', caption: 'Lanterna portátil c/ clip', captionSemAcentos: 'Lanterna portatil c/ clip', dimensions: '(22 x 4,5 cm)' },
{ codigo: '143205B', caption: 'Lanterna portátil c/ clip', captionSemAcentos: 'Lanterna portatil c/ clip', dimensions: '(22 x 4,5 cm)' },
{ codigo: '143205C', caption: 'Lanterna portátil c/ clip', captionSemAcentos: 'Lanterna portatil c/ clip', dimensions: '(22 x 4,5 cm)' },
{ codigo: '143206', caption: 'Pinça de metal c/ luz', captionSemAcentos: 'Pinca de metal c/ luz', dimensions: '(9 x 2,5 cm)' },
{ codigo: '143207A', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(9 x 3,3 x 0,7 cm)' },
{ codigo: '143207P', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(9 x 3,3 x 0,7 cm)' },
{ codigo: '143207V', caption: 'Lanterna plástica c/ chaveiro', captionSemAcentos: 'Lanterna plastica c/ chaveiro', dimensions: '(9 x 3,3 x 0,7 cm)' },
{ codigo: '143208A', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(9 x 3,5 cm)' },
{ codigo: '143209A', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(10 x 3,5 cm)' },
{ codigo: '143210', caption: 'Chaveiro c/ bússola e luz', captionSemAcentos: 'Chaveiro c/ bussola e luz', dimensions: '(9,5 x 3,5 cm)' },
{ codigo: '143211P', caption: 'Kit vinho c/ 4 pçs e estojo', captionSemAcentos: 'Kit vinho c/ 4 pcs e estojo', dimensions: '(16,5 x 14,5 x 5,5 cm)' },
{ codigo: '143212', caption: 'Porta batom', captionSemAcentos: 'Porta batom', dimensions: '(8,5 x 3,3 x 3,3 cm)' },
{ codigo: '143213A', caption: 'Chaveiro de metal', captionSemAcentos: 'Chaveiro de metal', dimensions: '(9 x 3,5 cm)' },
{ codigo: '143214', caption: 'Kit churrasco c/ 3 pçs', captionSemAcentos: 'Kit churrasco c/ 3 pcs', dimensions: '(36 x 9 x 4 cm)' },
{ codigo: '143215', caption: 'Kit churrasco c/ 4 pçs', captionSemAcentos: 'Kit churrasco c/ 4 pcs', dimensions: '(38 x 11,5 x 4 cm)' },
{ codigo: '236141', caption: 'Porta foto plástico 10x15 cm', captionSemAcentos: 'Porta foto plastico 10x15 cm', dimensions: '(10 x 15 cm)' },
{ codigo: '236145', caption: 'Porta foto plástico 10x15 cm', captionSemAcentos: 'Porta foto plastico 10x15 cm', dimensions: '(10 x 15 cm)' },
{ codigo: '236154', caption: 'Porta foto plástico 13x18 cm', captionSemAcentos: 'Porta foto plastico 13x18 cm', dimensions: '(13 x 18 cm)' },
{ codigo: '236155', caption: 'Porta foto plástico 13x18 cm', captionSemAcentos: 'Porta foto plastico 13x18 cm', dimensions: '(13 x 18 cm)' },
{ codigo: 'BJ9090', caption: 'Presilha p/ cabelo', captionSemAcentos: 'Presilha p/ cabelo', dimensions: '( cm)' },
    ];
                                                          

    $scope.enteredKonamiCode = false;
    $scope.checkKonamiCode = function(codigo) {
        if (codigo === 'konami') {
            $scope.enteredKonamiCode = true;
        }
    };
    
    $scope.produtoCorresponde = function(codigoProduto, descricaoProduto, descricaoProdutoSemAcentos, buscaCodigoProduto, buscaDescricaoProduto) {
        buscaCodigoProduto = buscaCodigoProduto || "";
        buscaDescricaoProduto = buscaDescricaoProduto || "";
        
        produtoCorresponde = codigoProduto.indexOf(buscaCodigoProduto.toUpperCase()) > -1;
        descricaoCorresponde = (descricaoProduto.toLowerCase().indexOf(buscaDescricaoProduto.toLowerCase()) > -1 || descricaoProdutoSemAcentos.toLowerCase().indexOf(buscaDescricaoProduto.toLowerCase()) > -1);

      if (buscaCodigoProduto === '') {
        produtoCorresponde = true;
      }
      if (buscaDescricaoProduto === '') {
        descricaoCorresponde = true;
      }

        return produtoCorresponde && descricaoCorresponde;
    };
  });
